# Generated by Django 5.2.14 on 2026-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinquiry",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
    ]
