# Generated by Django 5.2.14 on 2026-05-23 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machinery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant",
                    models.CharField(
                        choices=[("plant_1", "Plant I"), ("plant_2", "Plant II")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("image", models.ImageField(blank=True, upload_to="machinery/")),
                ("total_machines", models.PositiveIntegerField(blank=True, null=True)),
                ("make", models.CharField(blank=True, max_length=150)),
                (
                    "year_of_purchase",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("tonnage_or_capacity", models.CharField(blank=True, max_length=150)),
                (
                    "platen_size_or_dimensions",
                    models.CharField(blank=True, max_length=150),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "Machinery",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "Product categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                ("description", models.TextField()),
                ("customer", models.CharField(blank=True, max_length=150)),
                ("specification", models.TextField(blank=True)),
                ("extra_details", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.productcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
