# Generated by Django 5.2.14 on 2026-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0002_sitemediabanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="gstin",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="map_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitemediabanner",
            name="cta_button_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitemediabanner",
            name="cta_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
